import { Lexend } from "next/font/google";  // Importar Lexend desde next/font/google
import "./globals.css";

const lexend = Lexend({
  variable: "--font-lexend",  // Definir la variable para la fuente Lexend
  subsets: ["latin"],         // Usar el subconjunto de latín
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.variable}`}>  {/* Aplicar Lexend */}
        {children}
      </body>
    </html>
  );
}
